spring.application.name=droppii-test

# configure server port
server.port=8080

# configure db
spring.datasource.url=jdbc:mysql://localhost:3306/droppii
spring.datasource.username=root
spring.datasource.password=root_password123
#spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# configure pageable one-indexed
spring.data.web.pageable.one-indexed-parameters=true

#management.endpoints.web.exposure.include=*

# configure cache
spring.cache.type=redis
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}

# swagger-ui url api-docs
springdoc.swagger-ui.url=http://localhost:8080/v3/api-docs




